### ISSUE TITLE
The option of color for mode "reading".

### ISSUE THREAD

**Issue by rendel470** [billthefarmer/diary#102]
Your program is very good, but there is some color dissonance.

In settings there is "Theme/Dark"[or better DarkEd?]
|Use dark theme for editing|

What do you say about "Theme/DarkRd"?
|Use dark theme for reading|

**Comment by billthefarmer** [comment]
The markdown view is effectively a web page. You can have any theme you like using CSS or JavaScript.

**Comment by rendel470** [comment]
Sorry, of course, but I don’t understand anything about writing program styles! (Therefore, I asked you about the color option in the program)

I do (mostly) physical work and I don't have time to learn web page styles.
And even if I started to learn the styles of web pages, how do I apply them to the program? (To change in APK style.css and re-sign this APK?)

I just wanted a simple (IMHO) option for the "reading" mode. For reading ordinary diary texts. (With a dark background and light color of letters).

**Comment by citizen2947294** [comment]
It's pretty simple to set a dark background and light text with CSS through the menu (Edit styles...):

```
html {
    color: #eeeeee;
    background-color: #333333;
}
a {
    color: #ccccff
}
```

It's simple to switch back to dark on light too:

```
html {
    #color: #eeeeee;
    #background-color: #333333;
}
a {
    #color: #ccccff
}
```

I will say that I don't usually go in here and do it though because I'm usually just making a quick note and don't spend enough time in the app to care. If I am going to use Diary for a while I might though. It'd be nice to have a button or checkbox to select my preferred colors but I'm not inconvenienced by commenting out three lines of the stylesheet to switch colors.

**Comment by rendel470** [comment]
Thanks for your help, @citizen2947294.
 At first it worked.
Then I tried to make a comment (at the end of the file, through a new line, added and later erased, something like this: \* comment *\) and Edit styles.../style.css stopped working..

Does your screen blink when you swipe dates left/right? It’s strange. Only the flipping animation should blink and only in the light style of the "read" mode.
