### ISSUE TITLE
wrong CSS storage path

### ISSUE THREAD

**Issue by madeindjs** [billthefarmer/diary#112]
Relative to issue #111,  It seem that CSS path is wrong.

On version 1.55 with my SD card the storage path is: `/storage/7BCA-4B1A/storage/7BCA-4B1A/Diary/css`.

It seem to be a relative / absolute file path problem.

Android version: 8.0.0

**Comment by billthefarmer** [comment]
OK, I think I know what's happening. This is because of the restriction in later versions of android that you must use a content Uri to share files and the content resolver I am using can't cope with an SD card path. I will release a new version with a fix. I can't test it as I don't have a device with an SD card and the emulators won't let an app write to the SD card.

**Comment by madeindjs** [comment]
I can try to build and test the fix if you send me the branch name if you want it.

**Comment by billthefarmer** [comment]
It's the latest master release
[Diary-debug.zip](https://github.com/billthefarmer/diary/files/3801559/Diary-debug.zip)

**Comment by madeindjs** [comment]
It works! Thank you very much for your work.
