### ISSUE TITLE
Inserting an image link

### ISSUE THREAD

**Issue by spaceChRiS** [billthefarmer/diary#12]
Just an idea ...

I had a hard time to find a file manager on android that allows to copy a full path including filename of a picture file. Therefore I suggest the following:

![Insert image dialog](https://user-images.githubusercontent.com/16524534/27304418-4c639804-553e-11e7-92f6-5fcd43c2a15a.png)

![Insert image menu entry](https://user-images.githubusercontent.com/16524534/27304465-738dd4bc-553e-11e7-843f-8b74b78ba04f.png)

Probably, one could even borrow some code from [Signal](https://github.com/WhisperSystems/Signal-Android) where the most recent image files are displayed on top of the corresponding dialog.

Btw, the “Item 1” should of course be replaced by something like “2048” with the choice of “512”, “1024”, “1080”, ”1920”.

Since weeks I think about this feature and I know that at some point in time I was aware of something missing around this idea, but unfortunately I cannot remember. I think it will probably come to my mind again after I pressed “submit” …

**Comment by billthefarmer** [comment]
That was a bit easier because the code for adding images was already done for #13 and there is a mechanism for requesting a media picker. You can't 'copy' an image to a page or 'resize' it, you can only inset a markdown image link. The image will be inserted at the cursor position if there is one. I have included some code that resolves 'content' URIs to 'file' URIs. It isn't able to resolve URIs from sources like 'Recent', and 'Images', but it does from actual apps.
![screenshot_20170621-164556](https://user-images.githubusercontent.com/3448386/27393526-72ee1c42-56a1-11e7-9623-8e127d6d5196.png)
