### ISSUE TITLE
Files should be saved as .md instead of .txt

### ISSUE THREAD

**Issue by rubyDoomsday** [billthefarmer/diary#122]
Love the app! It is a solution that I have looking for for quite awhile. I planned in using this in conjunction with github for synchronization and backups. I am confused why the app saves the files as `.txt` instead of `.md` if it is using markdown syntax. There doesn't seem to be anyway to configure this.

**Comment by billthefarmer** [comment]
There are three reasons - I forked this app which already included the code to handle the file hierarchy, using markdown is an option - the app still works without, and it doesn't make any difference to the user what file extensions or hierarchy the app uses, it's hidden and only apparent if users go looking with a file manager.

**Comment by billthefarmer** [comment]
As an aside, I investigated cloud storage apps a while ago as the result of user requests. None of the android client apps I tried appeared to be capable of syncing a real storage folder. However [Syncthing](https://syncthing.net) does work and will sync a folder between devices and desktops. It's a bit complex to set up, but probably less so than git.

**Comment by rubyDoomsday** [comment]
Thanks! In my initial setup, I was trying to hook into a workflow I already used with Github for note-taking. I use vim with markdown as a note manager which I sync with Github on the back end. This allows me to leverage Git's markdown rendering through the browser, or other engines locally. Unfortunately, Github does not (automatically) render .txt files which is why I noticed the file extension. In my isolated little world, I save all markdown files with a .md or .markdown extension to comply with Github in addition to other ease of accessibility purposes. Long story short, I traded out Github in favor of auto-syncing to dropbox with [dropsync](https://play.google.com/store/apps/details?id=com.ttxapps.dropsync&hl=en_US). 

Ultimately, my goal wass to have access to the files on something other than my phone, but this setup might work as a way for you to synchronize data across two devices.

**Comment by gilcot** [comment]
But the true Markdown extension is `.markdown` ;-) The shortcut `.md` (unfortunately spreaded) is confusing as it can refer to many others formats. One of them is Modula source code, what makes _ViM_ natively misinterpret the highlighting many times :-(

**Comment by billthefarmer** [comment]
That's an interesting idea. I've never seen a `.markdown` file and I have been around a while. The version of vi that I use most, which comes with Git for Windows is quite happy highlighting `.md` files. It says it is...
```
$ vi --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 12 2019 08:44:38)
Included patches: 1-2292
Compiled by <redacted@gmail.com>
Huge version without GUI.  Features included (+) or not (-):
...
```
The mode lines don't give a clue as to what it thinks it's highlighting, but I'm fairly sure it thinks it's markdown.

**Comment by gilcot** [comment]
Hello @billthefarmer

I wasn't precise when I wrote that _ViM_ is confused about `.md` files. In fact, that happens when I start a fresh document and begin with titles for example. But as soon as I add more content (at least half screen of text) it's able to guess it's _Markdown_ file (but sometimes, I have to reopen/reload the file in order that takes effect) So, yes, it knows _Markdown_ by some heuristic, not by that extension (in fact not only by extension when they are shared by different languages)  
I'm using an older version (7) but I think syntax highlighting files haven't change for a while, and I can't remember anything about the internal engine on that, but I may be wrong :-) 

To know the highlighting rules applied, i.e. syntax rules loaded, just use [`:set filetype?` or it's shorter form `:se ft?`](https://stackoverflow.com/questions/2779379/find-what-filetype-is-loaded-in-vim) I also like comparing with the `file` command to see what is/should guess without extension and/or the associated mime-type.

About other extensions, I've already encountered `.markdown` by some rare _Github_ users (and also _Gitlab_ hehe), and [many others are accepted (tested with a temporary/sandbox repository)](https://superuser.com/questions/249436/file-extension-for-markdown-files/285878#285878) ;-)
