### ISSUE TITLE
Relative Path To Text File

### ISSUE THREAD

**Issue by citizen2947294** [billthefarmer/diary#123]
Sometime I have the notion to link to files (other than 'media' added through the menu and other entries) inside the diary directory (and even outside the diary directory). I checked the documentation and the past issues but I didn't see anything about accessing (text) files inside or outside the diary directory with relative paths. For example, say I want to open the file Diary/foo/bar.txt in Diary by using a link in Diary/2020/01/02.txt. I tried some different things:
```
[bar](../../foo/bar.txt)
[bar](Diary/foo/bar.txt)
[bar](/storage/emulated/0/Diary/foo/bar.txt)
[bar](/sdcard/Diary/foo/bar.txt).
```
I didn't find one that worked.

**Comment by billthefarmer** [comment]
If you add a link that resolves to a valid diary entry, the app will load it. Otherwise the embedded web view will attempt to load the text file or web page and give a helpful error message if it fails, like this:
```
[X](x.y)
```
### Web page not available
The web page at file:///storage/emulated/0/Diary/2020/02/x.y could not be loaded because:
net::ERR_FILE_NOT_FOUND

That file doesn't exist. Relative links are resolved to absolute file Uris relative to the current month folder, so if you put, for instance, `[X](../../x.y)` it would resolve to `file:///storage/emulated/0/Diary/x.y`. Absolute links will work as well. All the links you have shown above should work except for the second.

**Comment by citizen2947294** [comment]
I thought that was how it worked. I figured out what was keeping it from working: the browser option to use the browser for external links.

**Comment by billthefarmer** [comment]
Thank you - you just found a bug for me. Don't pass local Uris to external browser.
