### ISSUE TITLE
Feature request: customize file ext amd media file location ...

### ISSUE THREAD

**Issue by JackalZhao** [billthefarmer/diary#130]
Diary is such an underestimated app, I didn't expect a diary app could be so simple but powerful and small.

I only have some suggestions for the detail:

* since the Diary support markdown, I wish all the file extention name could be customed to md but not txt. ( a switch for users to choose in settings)

* If possible I wish users could customize that the media files would be copied to a customized subfolder but not the same folder with the diary file. Such as seting the path to be "${filename}.asset", for "/sdcard/Diary/2020/04/22.txt", all the media files would be copied to "/sdcard/Diary/2020/04/22.asset/" but not "/sdcard/Diary/2020/04", so we can prevent plenty of media files crams in one folder which is not easy to manage.

* The swipe detect is a little too sensitive, sometimes I just want to scroll up or down quickly, it would jump to next or previous day. It would be grateful to use floating buttons or stroking button gestures to flip pages.

**Comment by billthefarmer** [comment]
Markdown &ndash; this issue has already been raised, see #122. 
Copying &ndash; it's not a good idea to copy a lot of media files, IMHO, because you then have duplicate copies.
The swipe detect is deliberately one finger for scrolling and two finger for changing date. That is documented in the [README](https://github.com/billthefarmer/diary#swipe-left-and-right).

**Comment by JackalZhao** [comment]
> Markdown – this issue has already been raised, see #122.
> Copying – it's not a good idea to copy a lot of media files, IMHO, because you then have duplicate copies.
> The swipe detect is deliberately one finger for scrolling and two finger for changing date. That is documented in the [README](https://github.com/billthefarmer/diary#swipe-left-and-right).

Actually copying media files is due to the need of syncing between different devices like my computer and my two phone. If the media file is not with the entry at same place and using relative path, it would be impossible to view a file on different device while maintaining the same content.

**Comment by billthefarmer** [comment]
It would be possible to copy media files to a separate folder, but it is an issue that doesn't need fixing because, as I said here - https://github.com/billthefarmer/diary/issues/122#issuecomment-578074132, it doesn't make any difference to the user what file extensions or hierarchy the app uses, it's hidden and only apparent if users go looking with a file manager.

**Comment by JackalZhao** [comment]
> It would be possible to copy media files to a separate folder, but it is an issue that doesn't need fixing because, as I said here - [#122 (comment)](https://github.com/billthefarmer/diary/issues/122#issuecomment-578074132), it doesn't make any difference to the user what file extensions or hierarchy the app uses, it's hidden and only apparent if users go looking with a file manager.

I pull this issue because I personally have the habit of syncing the diary between my phones and computers, so I could edit the diary on the computer too. Changing the ext into md will help the computer to use the correct markdown editor to open it, not using the default notepad editor. 

I think people who have multiple devices will have the same requirement.
