### ISSUE TITLE
Missing "Cancel"-Option in page editor

### ISSUE THREAD

**Issue by just-Nob** [billthefarmer/diary#145]
I'm hardly missing the option to cancel my entries - especially on case of editing an existing page (i.e. an entry that wasn't empty when entering the page editor).

Even if I use the device's "back" button instead of the soft button to check the edited entries, the changes are stored into the diary.
So I see no chance to cancel my editing.

**Comment by billthefarmer** [comment]
That's interesting &ndash; this app has been out there for a few years, but nobody has asked for that before. I have added an extra toolbar icon which will only appear if there are changes to cancel. Unfortunately that pushes the navigation items over, so I may get complaints about that. The android [guidance](https://developer.android.com/reference/android/app/Activity#saving-persistent-state) on this says the back button should save the current state rather than cancel changes.

**Comment by just-Nob** [comment]
In fact, this is really remarkable - especially with an app like this, I think it's important to be able to discard the changes.

Of course it makes sense to have operating standards and to implement them if possible.  But I also think it is necessary not to slavishly stick to them, if it doesn't make too much sense.

At the moment, there is already a soft button to accept the changes, and the "Back" button also keeps the changes; so Tod is redundant. On the other hand, there is no way to discard the changes at the moment.

How about making the behavior of Android's "back" button configurable in the preferences?
1. always accept changes.
2. always cancel changes.
3. always ask if changes should be accepted or rejected.

Anyway, I'm curiously looking forward to the new version!

**Comment by billthefarmer** [comment]
Using markdown is an option, the accept/edit button is for switching between views, it saves the current entry if changed as a precaution against the unexpected. Otherwise the app saves changes when the user does something to change the current view. The back button is just one of the many ways to do that. I haven't pushed a new version with the cancel button because the previous one with the template changes hasn't appeared yet.

**Comment by just-Nob** [comment]
I was able to install version 1.69 via F-Droid today...

**Comment by just-Nob** [comment]
Please don't close that issue, in going to write some comments asap.
