### ISSUE TITLE
Duplicate entries in wrong month or year.

### ISSUE THREAD

**Issue by neil-edelman** [billthefarmer/diary#151]
Sometimes it silently saves (and replaces) a duplicate entry (file) in the wrong month or year. Only noticed after several years of entries under version control.

**Comment by billthefarmer** [comment]
I have looked at the code &ndash; it doesn't seem possible to store an entry in two places at once. What exactly do you mean by version control? Also, from [version 1.66](https://github.com/billthefarmer/diary/releases/tag/v1.66), new entries are stored with a `.md` extension rather than `.txt`.

**Comment by neil-edelman** [comment]
I am on 1.70. I turned off markdown; the file still saves with a `.txt` extension, (I like this.) I put a `git` repository under the directory where I save my Journal so I can do version control on my entries.

![Screenshot_20201130-182035_Termux](https://user-images.githubusercontent.com/774033/100648308-ad15bc00-3338-11eb-82d2-47029825909a.png)

This is an example: I was working on `2020/10/21.txt` and it saved a duplicate entry in `2017/11/21.txt`.

**Comment by billthefarmer** [comment]
I have released a new version with updated save logic which may stop that happening.

**Comment by neil-edelman** [comment]
I've updated and it hasn't had this problem since; will post another issue if this happens again.

**Comment by julianfoad** [comment]
This bug happened to me today on v1.82 and I can reproduce it.

Here is one way to reproduce it.
- go to a date that was empty (I chose a future date, 1st January 2022)
- click the "edit" icon and write some text ("Line 1.")
- click the "save" icon
- click the "edit" icon and add more text ("Line 2.")
- still in edit mode, choose "Go to date"
- in the date picker, two-finger scroll down to change the year (and don't click any date in the grid)
- the date picker now shows "Sunday 1 January 2023", but no circled day number on the grid
- hit "OK"

What happens now:
- the diary page returns to view mode, staying on the original date (1 January 2022), and discarding the edits and showing only "Line 1."
- a new file Diary/2023/01/01.md is created, containing a copy of the edited version of Diary/2022/01/01.md, that is "Line 1. Line 2." in this example

The same happens with a two-finger scroll sideways which changes the month.

Fortunately it seems not to overwrite it if there is an existing file of there is one
Hoping this is helpful to find the root cause.

**Comment by billthefarmer** [comment]
That was a good one, that's been in the app since I added the custom calendar. Sneaky calendar update via back door. That will be fixed in the next version.
