### ISSUE TITLE
Question not sure if bug or not

### ISSUE THREAD

**Issue by JunkyardCat** [billthefarmer/diary#168]
1. i tried searching a word in my past entries but nothing comes up. it can only search on current entry that im on.
2. i tried the add event funtion but its not adding event entries i made in my calendar app. im suing samsungs planner app.

**Comment by billthefarmer** [comment]
1. You need to use the **Find all** menu item
2.  Ensure that the app has permission to access your calendar. It asks when first run, but not again

I can't find a Samsung planner app, I put an event in the Samsung calendar on my tablet, added it to the diary and searched for the text. It didn't find the current match because the app hadn't saved it yet.

![Screenshot_20210509-150632_Diary 1](https://user-images.githubusercontent.com/3448386/117576428-e0295c00-b0dd-11eb-87e5-84826d03cf3d.jpg)

**Comment by billthefarmer** [comment]
> previous
next
today
go to date...
**>>> find all... <<<**
share...
add time
add events
add media...
edit styles...
edit script...
backup
settings

If you want to add an event to the diary you must have the diary entry for that date open in the app. The app only adds events for the current entry.
