### ISSUE TITLE
Weird behavior while searching in edit mode

### ISSUE THREAD

**Issue by uli-on** [billthefarmer/diary#173]
Hi Bill!

I'm having a problem about where and where not the focus of Diary lies.

Steps to reproduce are:
1. Enter edit mode
1. Select "Find..." from the menu. (In case it matters: I've a small screen, Find is in the three-dot-menu)
1. Enter a search term
2. Tap "Back" in the navigation bar to fold in the virtual keyboard and see more of the text. That seems(!) also to remove focus from the search's text input field.
3. Try to edit the text, here: Press delete
4. Result: The search term is removed in one as if it was completely marked and focus had been on the search input field, the page scrolls up.

OK, I thought, graphical glitch, i.e. Android's fault, focus is in fact on the search field, but tzhe cursor just isn't displayed. So after folding in the keyboard in step 4 I additionally clicked into the main text (the actual diary text) to set focus on that very area. Then I scrolled the text to the word I actually wanted to edit, clicked the text again (which should also set focus on the main text area) in order to bring back the keyboard and pushed Delete. 
Result: Same as above, the search term is removed, the page scrolls up.

I just tested a little further and found that pressing any letter (not only the delete key) deletes the search term and scrolls to top. *And* enters the letter, additionally. 

I hope that's fixable as my entries tend to be longish so searching is often necessary before correcting. 
Thanks for your struggles!

EDIT
Technical corner stones: 
- Diary v1.79
- Android 6.0.1
- Webview 92.0.4515.115
- Moto G4
- Tested on Floris Board/OpenBoard/Swiftkey with same results.

**Comment by billthefarmer** [comment]
The search widget, once you start it, takes over the toolbar and does it's own thing. The only thing the developer can do is find and highlight the text, or in the case of the web view that handles the markdown view, it does it all itself. In the case of a small phone it can be almost useless, because the keyboard UI can take over the whole display, like this…

![Screenshot_20210731-122218 1](https://user-images.githubusercontent.com/3448386/127738470-8e57667a-6b65-4b68-b25b-d40cd1911b20.png)

There's not a lot the developer can do about that. In the case of touching the text view, the first keystroke is acted on in the text view, then the focus immediately returns to the search widget. The developer doesn't get a look in. So there's not a lot I can do about it apart from starting again from scratch. If you dismiss the search widget, the edit cursor stays where you put it.

**Comment by uli-on** [comment]
Great that you amended your reply about the last paragraph. That's a great solution, Bill, I didn't know I could do that. Asking really paid off, thanks! 

If you haven't already, adding that paragraph to the help/introductory file would be welcome by many, I think.
