### ISSUE TITLE
Feature Request: Keep image filename when "copying to current folder"

### ISSUE THREAD

**Issue by YMan84** [billthefarmer/diary#177]
I really like the "Copy Images" option that the app provides. Makes it super easy to just open up the directory in Typora and add/edit entries while i'm on a computer. I think it would be much more useful if the copied images would keep their filenames when they were copied over, this way any photos/screenshots i attach keep their timestamped filenames and it makes it much more obvious which files are attached to which entries. 

Thanks for all the great work on this app. Found it a couple of days ago and have been really enjoying it and am seriously considering about moving over my 8 year's worth of [Rednotebook ](https://rednotebook.sourceforge.io/) notes over to markdown so that i have cross platform access to them.

**Comment by billthefarmer** [comment]
This is possible. I assume the contributor who wrote this used UUIDs to avoid file name collisions, otherwise you are into Filename_1, Filename_2, etc. The other problem is that this only works if the file utilities are able to resolve the URI. It usually works if the image is opened by the app, not necessarily if shared by another app.
