### ISSUE TITLE
suggestion: migrating from webview to markwon.

### ISSUE THREAD

**Issue by cloneconf** [billthefarmer/diary#180]
This will properly improve the performance when the user switch between edit and view mode. (yeah i mean that blink...)
Otherwise, i loved the app and i personally used it and it's just unquie ;)

**Comment by billthefarmer** [comment]
I just had a look at markwon, and although it may possibly be faster, it uses the same markdown library that I am using. The markdown in this app only gets reinterpreted when it is changed. The 'blink' is mainly due to the animation used for the switch. There is a long tradition, dating back to DOS days, of ensuring there is a slight delay when the user does something, otherwise they don't think the app has done anything. Also the web view allows styles, scripts and limited web browsing following links.
As an example of how fast android can be, if you don't put an animation in, try changing the theme in the settings, it's virtually instantaneous, even on my eight year old Moto G. It's not just redrawing the screen, it's recreating the associated activity. You can see the same thing, with an animation, by rotating the phone. That's also recreating the activity, but hidden by the rotation animation.

**Comment by cloneconf** [comment]
You are right webview provide a lot of features that is either hard or impossible to do in markwon.
This was just an idea...
Otherwise keep up on improving the app :)
