### ISSUE TITLE
vimwiki diary compatibility 

### ISSUE THREAD

**Issue by linuxcaffe** [billthefarmer/diary#19]
I'm using termux (termux.com, a linux emulator) on my phone, with vim and vimwiki (vimwiki.github.io, a personal wiki for vim) and vimwiki has a diary component, that consists of a file-per-day, and also supports markdown. 

This feature request is for a settings option that
a) can determine whether termux >> vim >> vimwiki is installed, and
b) can configure diary app to use the vimwiki-diary folder(s).

So that I can easily make vimwiki-diary entries, and acces previous ones, from my android.
thanks!

**Comment by billthefarmer** [comment]
It's possible for an app to determine if another app is installed - so diary could detect termux, but I don't think it's possible to find out any more about termux plugins and plugins for plugins due to the android security system. However diary already has the option to change the storage location.
