### ISSUE TITLE
Undo feature

### ISSUE THREAD

**Issue by hellpe** [billthefarmer/diary#191]
I've accidentaly deleted some text and I cannot find an "undo" button. Is that feature implemented?

**Comment by billthefarmer** [comment]
When you enter text, a **Cancel** button will appear in the toolbar. Tapping it will undo any edits since the entry was opened for editing. If you want to keep some changes, select and copy them before, then paste them back in again. The [EditText](https://developer.android.com/reference/android/widget/EditText) API used does not support incremental undo/redo like some editors. This is documented in the [README](https://github.com/billthefarmer/diary#editing) and the [help](https://github.com/billthefarmer/diary/blob/master/data/help.md#editing) text loaded when the app is first used.

**Comment by hellpe** [comment]
Thanks for the clarification! I was looking for the "undo" word in the README and couldn't find it.

**Comment by steko** [comment]
I just wanted to share my personal experience of **losing** entire diary entries that I had typed, by accidentally tapping the CANCEL button. The CANCEL button will delete all newly added content without any confirmation, even if the entry for that day was empty in the beginning.

**Comment by billthefarmer** [comment]
See #145.

**Comment by steko** [comment]
Thank you for adding the confirmation dialog in the 1.94 release! :heart:
