### ISSUE TITLE
Inexistent default backup path

### ISSUE THREAD

**Issue by frmayall1978** [billthefarmer/diary#223]
[No issue template, so will try my best keeping this one organised and readable]

The backup button in the top-right menu suggests the default path to be "/storage/emulated/0.zip", which isn't a thing nowadays. When changed to something acceptable, such as "/storage/emulated/0/diary.zip", it creates an archive that doesn't seem to stop growing and, after about 15 seconds of its existence, is 200mb big, which seems too much for a 233kb application with 3 diary notes in it. You'll find a screenshot of the suggested backup file attached, just in case.

Let me know if I can be of any help.

EDIT: Forgot to mention that the archive created seems to be corrupted, so nothing apparent is in it.

![screenshot](https://github.com/billthefarmer/diary/assets/90851285/a3468f18-bccc-47fc-b2bf-0092db2e3a6a)

**Comment by billthefarmer** [comment]
That looks to be to be due to the default diary folder being changed from 'Diary' to ''. The backup function uses that for the name of the zip file. You then went on to attempt to store the whole of your device storage (storage/emulated/0) in a zip file.

![Screenshot_20240129-085009 1](https://github.com/billthefarmer/diary/assets/3448386/7d1d01d9-b2e2-4c22-bc58-088b9dd440d9)

**Comment by frmayall1978** [comment]
Oh yes! Excuse the fuss. I, indeed, left the "Folder" field empty. It works as intended now. Thank you!

**Comment by frmayall1978** [comment]
Closing the issue now.
