### ISSUE TITLE
New function, search

### ISSUE THREAD

**Issue by Flavien06** [billthefarmer/diary#28]
Hi, It would propose to add a option to search word/text in all note.

**Comment by billthefarmer** [comment]
I will look at this. Finding text and highlighting it should be OK. The standard android search uses an button in the toolbar which expands when you touch it. I don't want to add another button to the toolbar because the next entry button would move to the menu, making navigation more awkward. I've already added to the functionality of the previous and next entry buttons on request because the today button is on the menu on phones.

**Comment by marcoM32** [comment]
IDEA: For add this and other functions we might think to adding a Navigation Drawer...

**Comment by billthefarmer** [comment]
Shouldn't be necessary - a search item in the menu still pops up the search box in the toolbar. Also I have a policy of not using the support libraries, which would be required for [Creating a Navigation Drawer](https://developer.android.com/training/implementing-navigation/nav-drawer.html), because they can make an enormous difference to the size of the app, see #2 and https://github.com/billthefarmer/diary/issues/2#issuecomment-306109500.

**Comment by billthefarmer** [comment]
Ok, that will be in the next version. It's a interactive search that changes as you type. The search button on the keyboard does find next.

**Comment by Flavien06** [comment]
It is a pity that it is not possible to search in all the notes.

**Comment by billthefarmer** [comment]
OK, I missed that, it will be in the next version. It may be a bit slow if you have a lot of long entries. When you touch the search item on the menu, as well as searching the current entry, a `Find all` item will appear in the menu. Touching that will pop up a dialog of the entries that match, or all entries with no text. Touching an entry in the dialog will open that entry and highlight matches in the entry.
