### ISSUE TITLE
Request: dark theme

### ISSUE THREAD

**Issue by JobLeonard** [billthefarmer/diary#38]
So I just installed this apo via F-droid after burning out my eyes one time too many times with Google Keep when taking a quick note after midnight.

I figured the custom markdown styles would let me simply add some css to make the app dark. It almost worked! 

The only thing is: the editor remains a bright white! Which I suppose is good: a bad css theme shouldn't make the interface unusable.

Still, adding a simple dark theme (just invert the current one to white text on black background, really) would make this so much nicer to use at night.

**Comment by billthefarmer** [comment]
I haven't done this before because it makes no difference to the markdown view as it's effectively a very simple web browser. You would have to use styles, as you have done. It also makes the custom calendar look horrible because the calendar part has it's own styles and doesn't change, but the dialog it sits in does. I will experiment.

**Comment by billthefarmer** [comment]
OK, I have released a new version with the option of dark styles. F-Droid has been [very slow](https://github.com/billthefarmer/editor/issues/33#issuecomment-354011102) lately, so it may take some time to appear.
