### ISSUE TITLE
Markdown rendering issues

### ISSUE THREAD

**Issue by Self-Perfection** [billthefarmer/diary#45]
Here is example content:
```
10
--
[probably] this [link](http://ya.ru) will be a mess

Сон
---
example_function_name
```
This is how it looks in Diary app:
![screenshot_20180331_001_50](https://user-images.githubusercontent.com/3757038/38161882-b8030b90-34df-11e8-8cf4-116ef3d9d208.png)
But expected rendering should be like this (taken from https://github.com/gsantner/markor app)
![screenshot_20180331_002_50](https://user-images.githubusercontent.com/3757038/38161913-4437c0d8-34e0-11e8-8609-1e15c424e351.png)
or here is rendering by github for comparison:

-------
10
--
[probably] this [link](http://ya.ru) will be a mess

Сон
---
example_function_name

-------

I've even tested in https://remarkableapp.github.io/ as an example of desktop app and got expected output.

So here are list of issues:
* Wrong, greedy boundaries for link text
* Short dash markers for heading are not recognized
* Underscores inside words are treated as italics selection

I suppose Diary uses custom made markdown parser. What's your opinion on switching to existing any library to avoid manually handling all corner cases?

**Comment by billthefarmer** [comment]
I use a [MarkdownView](https://github.com/billthefarmer/MarkdownView), forked from [here](https://github.com/falnatsheh/MarkdownView) to fix some issues, which uses [MarkdownJ](https://github.com/myabc/markdownj). I have added several custom additions in response to suggestions, but implemented in the app. . I evaluated the available libraries at the time of writing the app and I don't propose to change it.

The app makes no claim to be a definitive implementation of Markdown, it is available as a convenient method of producing formatted diary entries, with some useful additions.

The GPL says:

>Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

**Comment by Self-Perfection** [comment]
From you quoting of GPL I inferred that you got feeling that I somehow push you, or blame you, or maybe demand something from you. That is not wot I implied.

As issues reporting is enabled for this project, users stories of issues encountered during app usage are welcome. So here is my story: I hoped that Diary might work as a convenient on-the-go viewer of my extensive diary that I keep in [Zim](http://zim-wiki.org/index.html), as Diary readme suggests that it can read markdown and Zim can export to markdown. It turns out that markdown exported Zim journal is almost compatible with diary format, just needs renaming '\*.markdown' files to '\*.txt', but there are also a bit of format incompatibility that I've described in this issue. Before reporting issue I've tried exported files with different markdown parsers to figure out if it zim exporting or Diary displaying bug, and it turns out that diary does not recognize completely markdown convention.

Anyway, thank you for your app maintenance, responses and patience.

**Comment by gilcot** [comment]
Unfortunately markdown is not fully and clearly defined, and they're many flavors around. 

Line beginning with at least triple small dash should read as line separator like does the diary. But they are also used to mark level two headers (some flavors require there's the same amount of dashes as characters in the previous line) ...except if there's a blank line before... I'm sure there's an entry in CommonMark about that ;-) 

Same gotcha for underscore in words: initial markdown says nothing about that! GitHub (with gfm) and others (all code writing related) add the exception (because such variable and function names are legion) I prefer the way diary behaves because that's what non-technical users expect (and what some blogs platforms and social networks do), and also because tech-users should know that such names (variables and functions etc) should be put between backtics or some characters (underscore and asterisc) must be escaped with backslash (and that works here too.) So there's clearly a bug in _Zim_ export here. :-)

**Comment by billthefarmer** [comment]
I hadn't noticed that a triple dash produces a line separator. I suspect there's more that I haven't found yet. I think the dash and equals underline are in some parsers for compatibility with an older markup convention.
