### ISSUE TITLE
feature request: templates

### ISSUE THREAD

**Issue by trmendes** [billthefarmer/diary#54]
What about having a way to create one or more templates so we can choose which one we would like to use when we start to edit our day.

**Comment by billthefarmer** [comment]
There's nothing stopping anyone doing that. Just store your templates somewhere in the past and copy them as required.

**Comment by thiswillbeyourgithub** [comment]
Hi, great app but is there a way to have each page pre filled with text ?

For example : I open today's page it there would already be this :
"calories eaten :
exercise : 
people seen :
today's log :"
and I would just have to fill it up. I tried to take a look at "styles" and "script" but can't be sure.

That would be a great enhancement I think because all the people looking for a daily ticking app (like tickmate on F-Droid) could use it.
