### ISSUE TITLE
Logo Proposal 

### ISSUE THREAD

**Issue by olayhemy** [billthefarmer/diary#62]
Hello,  I've created a new logo for this project as I've love to contribute to it. Below is the sample of how it looks like, check and ask for correction if necessary. Thanks 

![diary logo 2.png](https://steemitimages.com/DQmevGHhwscdfiEda8Exx1hufDj8pEgMFCaiyT2ys7nXmBN/diary%20logo%202.png)

**Comment by billthefarmer** [comment]
I have had several proposals of new icons for this app. I looked into the possibility of offering alternative icons within the app, but I don't think it is possible unless someone says otherwise.

However the app icon only appears in the launcher unless you are running Android 4 and there appear to be plenty of icon theme apps and apps for changing icons and launchers that can change app icons out there. So I intend to leave the icon as it is and if users would like a different one they can change it using an app or launcher.
