### ISSUE TITLE
Some dates gets unseen in landscape mode and I was not able to select unseen dates.

### ISSUE THREAD

**Issue by pzdawood** [billthefarmer/diary#63]
### Actual behaviour
When I open the Diary app in landscape mode and click on options botton. I choose Go to date option and click on this option. After clicking on this option all the dates are not appeared,some dates are unseen and I was not able to select them .
If I open this option in portable mode and rotate my phone in landscape mode. I have to select Go to option again . After clicking on this option similarly some dates are unseen.

### How to reproduce
* Download the Diary app from F-driod .
* Install this app.
* Open the diary app.
* Click on options botton .
* Select Go to date option.
* After clicking on this option some dates are unseen and was not able to select them .
* Browser:Diary
* Version :1.29
* Operating system:7.1.2
#### Recording of the bug
https://youtu.be/0xewdTcH8WU

**Comment by billthefarmer** [comment]
The video has been removed. I assume you are using the custom calendar. I will experiment with adding scrolling.

**Comment by billthefarmer** [comment]
I have tested adding a scroll view to the custom calendar. Unfortunately that is not very satisfactory either. The left and right buttons are obscured and won't scroll into view.

![device-2018-05-31-120205](https://user-images.githubusercontent.com/3448386/40779249-1d04fbcc-64cc-11e8-9f71-29683478698c.png)

I would suggest you use the date picker rather than the custom calendar in landscape.
