### ISSUE TITLE
feature request: password access

### ISSUE THREAD

**Issue by nutpantz** [billthefarmer/diary#65]
I would like to see a simple password access for the diary. Numeric would be fine up to 16 characters. I know everything can be read in the text files, but most people can't get passed the UI.

**Comment by billthefarmer** [comment]
This is in the same category as those who have asked for an encrypted diary. See #59 and #39. If you don't want people to read the diary encrypt the phone or use user accounts or a guest account.

**Comment by nutpantz** [comment]
Your the developer, it's your baby. Don't know how many people would agree to not have have any basic privacy options on a diary, but you know your users.

**Comment by billthefarmer** [comment]
I find this argument somewhat specious. If you don't secure your phone your emails, messages, address book, call log, secure messages, social media apps, etc, are all open to scrutiny unless you religiously log in and out of those that can be logged in and out of. Why should a diary app be any different? I don't believe in duplication of functionality already built in to all devices for just one app.

**Comment by nutpantz** [comment]
Well other than the fact that border agents can force you to unlock your phone but not your apps, police can force you to unlock you device with finger print or facial recognition but not your apps with a password. And a significant other gets to watch you unlock your phone 5000 times.I can't think of any reason to have a password on an app that people might write their personal thoughts and desires. A simple password every time it's opened just gives you a little more time to react if someone picks up your phone if it has not auto locked.

**Comment by billthefarmer** [comment]
There is another option I hadn't thought of. Some launchers, such as Trebuchet, which comes with LineageOS, implement secure folders which you can move sensitive apps to.

**Comment by nutpantz** [comment]
Yep that would be viable of the majority of people used trebuchet very few launchers have that feature, while very many diary/journal apps have some kind of password protection.. I'm not saying you have to implement it. But your app will be much more popular if the option for a password is there.  Myself I don't NEED encryption,(I'll have the directory attached
Archived with pgp monthly or weekly and transferred to rednotebook desktop. I hate having one encryption on my device and a different one on my phone for apps.) But I dont want anyone just reading my diary if they get my phone while it's unlocked. ( yes my gf is very curious, but she is worth it)

**Comment by kamilst96** [comment]
The issue seems open, so I'll try to add something from me.

In mobile systems, Android especially, the system itself is only a first line of security, and is always prone to fail. It's these inexperienced soldiers you send to die, before employing other divisions. In other words, it can never be assumed and trusted, that a device is secure.

Example? When it comes to Samsung devices with Android 7  and below, there were many tricks to access already enabled phone (it is secure when it's turned off, but when is it turned off in today's world?). Look for a trick involving fake calling via a COM port, then responding to call with SMS and sending an internet link, and then installing an app that would bypass security, if you're interested.

Nobody asks you to write a complex asymmetrical encryption. If someone wants it, they'd have some frickin app container for that already. A simple, password based, symmetrical algorithm would be fully sufficient.

Of course, whatever your decision will be, I am not bitching around. I really like your app, and wish you much success in the development world ;)

**Comment by billthefarmer** [comment]
One of the nice things about FOSS apps is that if it doesn't do what you want you can always fork it and add functionality. I forked this app originally.

I don't intend to add password protection and/or encryption to this app for many reasons, some mentioned above. there are also many issues that it would create:
* How to handle existing entries
* Dealing with users who have forgotten/lost their password
* Handling password changes or removal where the password is possibly a salt for the encryption. It would be necessary to do something like that as the source is visible, so you can't hide anything.
* All the things I haven't thought of which will certainly crop up

**Comment by kamilst96** [comment]
Then a simple single page protection would do. Simple if statement on if the page is encrypted (some header, or nonsensical character detection). This way you wouldn't have to worry about password change. Simply tell them to decrypt and encrypt again.

No, I don't expect you'll do it. It's just an idea added to an open issue, which indicates you're still open to suggestions. Maybe it's time to close it?

PS. I wouldn't use password protection anyway. What kind of secrets do people write in an app? 😂

**Comment by thiswillbeyourgithub** [comment]
I would just point out that I respectfully disagree with the opinion "it's not useful to allow encrypting of the app when the whole device can be encrypted" because device encryption is a particularly tricky functinonality to implement for custom ROM and many don't have it working, even LineageOS on some devices.
